2019-01-29 15:22:37,523 - ERROR - logging_test.py[:24] - error message
2019-01-29 15:22:37,523 - CRITICAL - logging_test.py[:25] - critical message
2019-01-29 15:26:35,417 - logging_test.py[line: 25] - ERROR - error message: 0
2019-01-29 15:26:35,417 - logging_test.py[line: 26] - CRITICAL - critical message: 0
2019-01-29 15:26:35,418 - logging_test.py[line: 25] - ERROR - error message: 1
2019-01-29 15:26:35,418 - logging_test.py[line: 26] - CRITICAL - critical message: 1
2019-01-29 15:26:35,419 - logging_test.py[line: 25] - ERROR - error message: 2
2019-01-29 15:26:35,419 - logging_test.py[line: 26] - CRITICAL - critical message: 2
2019-01-29 15:26:35,419 - logging_test.py[line: 25] - ERROR - error message: 3
2019-01-29 15:26:35,419 - logging_test.py[line: 26] - CRITICAL - critical message: 3
2019-01-29 15:26:35,420 - logging_test.py[line: 25] - ERROR - error message: 4
2019-01-29 15:26:35,420 - logging_test.py[line: 26] - CRITICAL - critical message: 4
2019-01-29 15:26:35,420 - logging_test.py[line: 25] - ERROR - error message: 5
2019-01-29 15:26:35,420 - logging_test.py[line: 26] - CRITICAL - critical message: 5
2019-01-29 15:26:35,420 - logging_test.py[line: 25] - ERROR - error message: 6
2019-01-29 15:26:35,420 - logging_test.py[line: 26] - CRITICAL - critical message: 6
2019-01-29 15:26:35,421 - logging_test.py[line: 25] - ERROR - error message: 7
2019-01-29 15:26:35,421 - logging_test.py[line: 26] - CRITICAL - critical message: 7
2019-01-29 15:26:35,421 - logging_test.py[line: 25] - ERROR - error message: 8
2019-01-29 15:26:35,421 - logging_test.py[line: 26] - CRITICAL - critical message: 8
2019-01-29 15:26:35,421 - logging_test.py[line: 25] - ERROR - error message: 9
2019-01-29 15:26:35,421 - logging_test.py[line: 26] - CRITICAL - critical message: 9
2019-01-29 15:35:00,539 - logging_test.py[line: 32] - ERROR - error message: 0
2019-01-29 15:35:00,540 - logging_test.py[line: 33] - CRITICAL - critical message: 0
2019-01-29 15:35:01,543 - logging_test.py[line: 32] - ERROR - error message: 1
2019-01-29 15:35:01,543 - logging_test.py[line: 33] - CRITICAL - critical message: 1
2019-01-29 15:35:02,544 - logging_test.py[line: 32] - ERROR - error message: 2
2019-01-29 15:35:02,544 - logging_test.py[line: 33] - CRITICAL - critical message: 2
2019-01-29 15:35:03,546 - logging_test.py[line: 32] - ERROR - error message: 3
2019-01-29 15:35:03,547 - logging_test.py[line: 33] - CRITICAL - critical message: 3
2019-01-29 15:35:04,550 - logging_test.py[line: 32] - ERROR - error message: 4
2019-01-29 15:35:04,551 - logging_test.py[line: 33] - CRITICAL - critical message: 4
2019-01-29 15:35:05,554 - logging_test.py[line: 32] - ERROR - error message: 5
2019-01-29 15:35:05,554 - logging_test.py[line: 33] - CRITICAL - critical message: 5
2019-01-29 15:35:06,557 - logging_test.py[line: 32] - ERROR - error message: 6
2019-01-29 15:35:06,558 - logging_test.py[line: 33] - CRITICAL - critical message: 6
2019-01-29 15:35:07,561 - logging_test.py[line: 32] - ERROR - error message: 7
2019-01-29 15:35:07,562 - logging_test.py[line: 33] - CRITICAL - critical message: 7
2019-01-29 15:35:08,564 - logging_test.py[line: 32] - ERROR - error message: 8
2019-01-29 15:35:08,565 - logging_test.py[line: 33] - CRITICAL - critical message: 8
2019-01-29 15:35:09,569 - logging_test.py[line: 32] - ERROR - error message: 9
2019-01-29 15:35:09,570 - logging_test.py[line: 33] - CRITICAL - critical message: 9
