2019-01-29 15:22:37,523 - ERROR - logging_test.py[:24] - error message
2019-01-29 15:22:37,523 - CRITICAL - logging_test.py[:25] - critical message
2019-01-29 15:26:35,417 - logging_test.py[line: 25] - ERROR - error message: 0
2019-01-29 15:26:35,417 - logging_test.py[line: 26] - CRITICAL - critical message: 0
2019-01-29 15:26:35,418 - logging_test.py[line: 25] - ERROR - error message: 1
2019-01-29 15:26:35,418 - logging_test.py[line: 26] - CRITICAL - critical message: 1
2019-01-29 15:26:35,419 - logging_test.py[line: 25] - ERROR - error message: 2
2019-01-29 15:26:35,419 - logging_test.py[line: 26] - CRITICAL - critical message: 2
2019-01-29 15:26:35,419 - logging_test.py[line: 25] - ERROR - error message: 3
2019-01-29 15:26:35,419 - logging_test.py[line: 26] - CRITICAL - critical message: 3
2019-01-29 15:26:35,420 - logging_test.py[line: 25] - ERROR - error message: 4
2019-01-29 15:26:35,420 - logging_test.py[line: 26] - CRITICAL - critical message: 4
2019-01-29 15:26:35,420 - logging_test.py[line: 25] - ERROR - error message: 5
2019-01-29 15:26:35,420 - logging_test.py[line: 26] - CRITICAL - critical message: 5
2019-01-29 15:26:35,420 - logging_test.py[line: 25] - ERROR - error message: 6
2019-01-29 15:26:35,420 - logging_test.py[line: 26] - CRITICAL - critical message: 6
2019-01-29 15:26:35,421 - logging_test.py[line: 25] - ERROR - error message: 7
2019-01-29 15:26:35,421 - logging_test.py[line: 26] - CRITICAL - critical message: 7
2019-01-29 15:26:35,421 - logging_test.py[line: 25] - ERROR - error message: 8
2019-01-29 15:26:35,421 - logging_test.py[line: 26] - CRITICAL - critical message: 8
2019-01-29 15:26:35,421 - logging_test.py[line: 25] - ERROR - error message: 9
2019-01-29 15:26:35,421 - logging_test.py[line: 26] - CRITICAL - critical message: 9
2019-01-29 15:35:00,539 - logging_test.py[line: 32] - ERROR - error message: 0
2019-01-29 15:35:00,540 - logging_test.py[line: 33] - CRITICAL - critical message: 0
2019-01-29 15:35:01,543 - logging_test.py[line: 32] - ERROR - error message: 1
2019-01-29 15:35:01,543 - logging_test.py[line: 33] - CRITICAL - critical message: 1
2019-01-29 15:35:02,544 - logging_test.py[line: 32] - ERROR - error message: 2
2019-01-29 15:35:02,544 - logging_test.py[line: 33] - CRITICAL - critical message: 2
2019-01-29 15:35:03,546 - logging_test.py[line: 32] - ERROR - error message: 3
2019-01-29 15:35:03,547 - logging_test.py[line: 33] - CRITICAL - critical message: 3
2019-01-29 15:35:04,550 - logging_test.py[line: 32] - ERROR - error message: 4
2019-01-29 15:35:04,551 - logging_test.py[line: 33] - CRITICAL - critical message: 4
2019-01-29 15:35:05,554 - logging_test.py[line: 32] - ERROR - error message: 5
2019-01-29 15:35:05,554 - logging_test.py[line: 33] - CRITICAL - critical message: 5
2019-01-29 15:35:06,557 - logging_test.py[line: 32] - ERROR - error message: 6
2019-01-29 15:35:06,558 - logging_test.py[line: 33] - CRITICAL - critical message: 6
2019-01-29 15:35:07,561 - logging_test.py[line: 32] - ERROR - error message: 7
2019-01-29 15:35:07,562 - logging_test.py[line: 33] - CRITICAL - critical message: 7
2019-01-29 15:35:08,564 - logging_test.py[line: 32] - ERROR - error message: 8
2019-01-29 15:35:08,565 - logging_test.py[line: 33] - CRITICAL - critical message: 8
2019-01-29 15:35:09,569 - logging_test.py[line: 32] - ERROR - error message: 9
2019-01-29 15:35:09,570 - logging_test.py[line: 33] - CRITICAL - critical message: 9
2019-03-17 22:58:08,652 - logging_test.py[line: 35] - ERROR - error message: 0
2019-03-17 22:58:08,653 - logging_test.py[line: 36] - CRITICAL - critical message: 0
2019-03-17 22:58:09,659 - logging_test.py[line: 35] - ERROR - error message: 1
2019-03-17 22:58:09,659 - logging_test.py[line: 36] - CRITICAL - critical message: 1
2019-03-17 22:58:10,660 - logging_test.py[line: 35] - ERROR - error message: 2
2019-03-17 22:58:10,660 - logging_test.py[line: 36] - CRITICAL - critical message: 2
2019-03-17 22:58:11,661 - logging_test.py[line: 35] - ERROR - error message: 3
2019-03-17 22:58:11,661 - logging_test.py[line: 36] - CRITICAL - critical message: 3
2019-03-17 22:58:12,663 - logging_test.py[line: 35] - ERROR - error message: 4
2019-03-17 22:58:12,663 - logging_test.py[line: 36] - CRITICAL - critical message: 4
2019-03-17 22:58:13,664 - logging_test.py[line: 35] - ERROR - error message: 5
2019-03-17 22:58:13,665 - logging_test.py[line: 36] - CRITICAL - critical message: 5
2019-03-17 22:58:14,666 - logging_test.py[line: 35] - ERROR - error message: 6
2019-03-17 22:58:14,666 - logging_test.py[line: 36] - CRITICAL - critical message: 6
2019-03-17 22:58:15,668 - logging_test.py[line: 35] - ERROR - error message: 7
2019-03-17 22:58:15,668 - logging_test.py[line: 36] - CRITICAL - critical message: 7
2019-03-17 22:58:16,668 - logging_test.py[line: 35] - ERROR - error message: 8
2019-03-17 22:58:16,669 - logging_test.py[line: 36] - CRITICAL - critical message: 8
2019-03-17 22:58:17,670 - logging_test.py[line: 35] - ERROR - error message: 9
2019-03-17 22:58:17,670 - logging_test.py[line: 36] - CRITICAL - critical message: 9
2019-03-17 22:58:37,275 - logging_test.py[line: 35] - ERROR - error message: 0
2019-03-17 22:58:37,275 - logging_test.py[line: 36] - CRITICAL - critical message: 0
2019-03-17 22:58:38,275 - logging_test.py[line: 35] - ERROR - error message: 1
2019-03-17 22:58:38,275 - logging_test.py[line: 36] - CRITICAL - critical message: 1
2019-03-17 22:58:39,278 - logging_test.py[line: 35] - ERROR - error message: 2
2019-03-17 22:58:39,278 - logging_test.py[line: 36] - CRITICAL - critical message: 2
2019-03-17 22:58:40,278 - logging_test.py[line: 35] - ERROR - error message: 3
2019-03-17 22:58:40,278 - logging_test.py[line: 36] - CRITICAL - critical message: 3
2019-03-17 22:58:41,281 - logging_test.py[line: 35] - ERROR - error message: 4
2019-03-17 22:58:41,281 - logging_test.py[line: 36] - CRITICAL - critical message: 4
2019-03-17 22:58:42,282 - logging_test.py[line: 35] - ERROR - error message: 5
2019-03-17 22:58:42,282 - logging_test.py[line: 36] - CRITICAL - critical message: 5
2019-03-17 22:58:43,282 - logging_test.py[line: 35] - ERROR - error message: 6
2019-03-17 22:58:43,282 - logging_test.py[line: 36] - CRITICAL - critical message: 6
2019-03-17 22:58:44,282 - logging_test.py[line: 35] - ERROR - error message: 7
2019-03-17 22:58:44,282 - logging_test.py[line: 36] - CRITICAL - critical message: 7
2019-03-17 22:58:45,283 - logging_test.py[line: 35] - ERROR - error message: 8
2019-03-17 22:58:45,283 - logging_test.py[line: 36] - CRITICAL - critical message: 8
2019-03-17 22:58:46,283 - logging_test.py[line: 35] - ERROR - error message: 9
2019-03-17 22:58:46,283 - logging_test.py[line: 36] - CRITICAL - critical message: 9
2019-03-17 23:00:48,100 - logging_test.py[line: 35] - ERROR - error message: 0
2019-03-17 23:00:48,100 - logging_test.py[line: 36] - CRITICAL - critical message: 0
2019-03-17 23:00:49,101 - logging_test.py[line: 35] - ERROR - error message: 1
2019-03-17 23:00:49,101 - logging_test.py[line: 36] - CRITICAL - critical message: 1
2019-03-17 23:00:50,101 - logging_test.py[line: 35] - ERROR - error message: 2
2019-03-17 23:00:50,101 - logging_test.py[line: 36] - CRITICAL - critical message: 2
2019-03-17 23:00:51,102 - logging_test.py[line: 35] - ERROR - error message: 3
2019-03-17 23:00:51,102 - logging_test.py[line: 36] - CRITICAL - critical message: 3
2019-03-17 23:00:52,103 - logging_test.py[line: 35] - ERROR - error message: 4
2019-03-17 23:00:52,103 - logging_test.py[line: 36] - CRITICAL - critical message: 4
2019-03-17 23:00:53,103 - logging_test.py[line: 35] - ERROR - error message: 5
2019-03-17 23:00:53,103 - logging_test.py[line: 36] - CRITICAL - critical message: 5
2019-03-17 23:00:54,103 - logging_test.py[line: 35] - ERROR - error message: 6
2019-03-17 23:00:54,103 - logging_test.py[line: 36] - CRITICAL - critical message: 6
2019-03-17 23:00:55,104 - logging_test.py[line: 35] - ERROR - error message: 7
2019-03-17 23:00:55,104 - logging_test.py[line: 36] - CRITICAL - critical message: 7
2019-03-17 23:00:56,105 - logging_test.py[line: 35] - ERROR - error message: 8
2019-03-17 23:00:56,106 - logging_test.py[line: 36] - CRITICAL - critical message: 8
2019-03-17 23:00:57,107 - logging_test.py[line: 35] - ERROR - error message: 9
2019-03-17 23:00:57,107 - logging_test.py[line: 36] - CRITICAL - critical message: 9
